<?php 
/*
 * Implementation of hook_init()
 */
function cookie_reload_init(){

  drupal_add_js(drupal_get_path('module', 'cookie_reload').'/js/cookie.js' );
  drupal_add_js(drupal_get_path('module', 'cookie_reload').'/js/params.js' );
  drupal_add_js(drupal_get_path('module', 'cookie_reload').'/js/jquery.hashchange.min.js' );
}
/*
 * Implementation of hook_init()
 */
function cookie_reload_menu(){
  
}