<?php

function gallery_main_image_menu() {
  $items['gallery-image/%'] = array(
      'title' => 'Contact information',
      'page callback' => 'gallery_image_page',
      'type' => MENU_CALLBACK,
      'access callback' => 'user_access',
      'access arguments' => array('see front page'),
      'page arguments' => array(1),
  );
  
  return $items;
}
function gallery_main_image_theme(){
   return array(
      'gallery_image_page' => array(
          'template' => 'gallery_main_image',
          'arguments' => array('node' => NULL),
      )
  );
}
function gallery_image_page($nid) {
  $node = node_load(array('nid'=>$nid));
  $teaser = false;
  $page = true;
  $node = node_build_content($node, $teaser, $page);

  
  $content = drupal_render($node->content);
  if ($teaser) {
    $node->teaser = $content;
    unset($node->body);
  }
  else {
    $node->body = $content;
    unset($node->teaser);
  }

  // Allow modules to modify the fully-built node.
  node_invoke_nodeapi($node, 'alter', $teaser, $page);
  
  echo theme('gallery_image_page',$node);
}